openapi: 3.0.0
info:
  title: Fitness Coaching App Backend API
  description: Backend API for Fitness Coaching App
  version: 0.0.5

servers:
  - url: https://asia-southeast1-fitness-coaching-app.cloudfunctions.net/dev-api
    description: Development server
  - url: https://asia-southeast1-fitness-coaching-app.cloudfunctions.net/fca-api
    description: Production server

paths:
  /auth/signIn:
    $ref: './paths/auth/signIn.yaml'