openapi: 3.0.0
info:
  title: Fitness Coaching App Backend API
  description: Backend API for Fitness Coaching App
  version: 0.0.5

servers:
  - url: https://asia-southeast1-fitness-coaching-app.cloudfunctions.net/dev-api
    description: Development server
  - url: https://asia-southeast1-fitness-coaching-app.cloudfunctions.net/fca-api
    description: Production server

components:
  securitySchemes:
    BearerRefreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BearerAccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/signIn:
    $ref: './paths/auth/signIn.yaml'
  /auth/register:
    $ref: './paths/auth/register.yaml'
  /auth/verifyEmail/{token}:
    $ref: './paths/auth/verifyEmail@{token}.yaml'
  /auth/refreshToken:
    $ref: './paths/auth/refreshToken.yaml'

  /user/editUserInfo:
    $ref: './paths/user/editUserInfo.yaml'
  /user/editProfilePicture:
    $ref: './paths/user/editProfilePicture.yaml'

