# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to GCP

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Copy package.json to build/src folder & Change target
      run: |
        jq '.main = "index.js"' package.json > build/src/package.json
        cat build/src/package.json
        
    - name: Folder Hash
      uses: theowenyoung/folder-hash@v2
      id: folder-hash
      with:
        path: ./src
        
    - name: Cache Build File
      uses: actions/cache@v2.1.6
      with:
        path: ./build
        key: ${{ runner.os }}-fca-build-${{ steps.folder-hash.outputs.hash }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
    - uses: actions/checkout@v2
    - name: Folder Hash
      uses: theowenyoung/folder-hash@v2
      id: folder-hash
      with:
        path: ./src
    - name: Restore Build File
      uses: actions/cache@v2.1.6
      with:
        path: ./build
        key: ${{ runner.os }}-fca-build-${{ steps.folder-hash.outputs.hash }}
    - run: ls -l build/src
    - name: Cloud Functions Deploy
      uses: google-github-actions/deploy-cloud-functions@v0.1.2
      id: deploy
      with:
        name: fca-api
        # Project to deploy the function in.
        project_id: ${{ secrets.RUN_PROJECT }}
        # The email address of the IAM service account associated with the function at runtime.
        service_account_email: ${{ secrets.SA_EMAIL }}
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        # Region to deploy the function in. Defaults to us-central1, if not specified.
        region: asia-southeast1
        # Path to function deployment directory within the source repo.
        source_dir: ./build/src
        # Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. 
        entry_point: functions.api
        # Runtime to use for the function.
        runtime: nodejs14
  
